default: &default
  adapter: postgresql
  encoding: unicode
  host: db # From docker-compose service's name
  username: postgres
  password: <%= ENV['PG_PASSWORD'] %> # From web's service environment


development:
  <<: *default
  database: db/veicsuport_development

test:
  <<: *default
  database: db/veicsuport_test

production:
  <<: *default
  database: db/veicsuport
